"""make stripe_subscription_id nullable

Revision ID: 28955dd74cb4
Revises: 757ccb49c9c7
Create Date: 2026-07-09 17:12:24.124809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28955dd74cb4'
down_revision: Union[str, Sequence[str], None] = '757ccb49c9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_id'), 'idempotency_keys', ['id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_orders_stripe_checkout_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stripe_payment_intent_id'), table_name='orders')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'stripe_checkout_session_id')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'stripe_payment_intent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('stripe_checkout_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_index(op.f('ix_orders_stripe_payment_intent_id'), 'orders', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_orders_stripe_checkout_session_id'), 'orders', ['stripe_checkout_session_id'], unique=True)
    op.drop_column('orders', 'product_id')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
