"""add_race_condition_fixes

Revision ID: 2df84e084542
Revises: 88a84e74aa5c
Create Date: 2026-07-10 15:11:11.321140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df84e084542'
down_revision: Union[str, Sequence[str], None] = '88a84e74aa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('status', sa.String(), nullable=False))
    op.add_column('idempotency_keys', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('idempotency_keys', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('idempotency_keys', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('payments', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_column('payments', 'idempotency_key')
    op.drop_column('idempotency_keys', 'updated_at')
    op.drop_column('idempotency_keys', 'error_message')
    op.drop_column('idempotency_keys', 'attempts')
    op.drop_column('idempotency_keys', 'status')
    # ### end Alembic commands ###
