"""make stripe_subscription_id nullable

Revision ID: 757ccb49c9c7
Revises: 5bccd7027522
Create Date: 2026-07-09 16:36:21.097722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757ccb49c9c7'
down_revision: Union[str, Sequence[str], None] = '5bccd7027522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
